School/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using School.Data.Models;
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using System.Collections.Generic;
using Microsoft.Net.Http.Headers;

namespace School.Controllers
{
    public class ClientController : Controller
    {
        private int id;
        private static Person thisAccount;
        public static List<Person> FindedParents;
        private readonly IHostingEnvironment _environment;

        public ClientController(IHostingEnvironment IHostingEnvironment)
        {
            _environment = IHostingEnvironment;
        }
       
        public ViewResult Index()
        {
            this.id = AccountController.id;
            thisAccount = AccountController.current;
            ViewBag.thisAccount = thisAccount;
            return View();
        }
        public ViewResult Parents()
        {
            WorkWithDB workWithDB = new WorkWithDB();
            FindedParents = workWithDB.getParents();
            return View();
        }
        public IActionResult ParentsConnections()
        {
            if (!(AccountController.current.level > 5)) return Redirect("/Home/error403");

            WorkWithDB workWithDB = new WorkWithDB();
            FindedParents = workWithDB.getParents();
            return View();
        }
        public ViewResult setConnection(int idParent, int idChild)
        {
            WorkWithDB workWithDB = new WorkWithDB();
            ViewBag.ConnectionPC = $"теперь родитель (ID {idParent}) связан с ребенком (ID {idChild})";
            if (!workWithDB.UpdateParentChild(idParent, idChild)) ViewBag.ConnectionPC = "Не удалость связать";
            FindedParents = workWithDB.getParents();
            return View("ParentsConnections");
        }
        public ViewResult getExFindedParent(string LastName, string idParent, string LastNameChild, string idchild)
        {
            LastName = LastName == null ? "%" : "%" + LastName + "%";
            idParent = idParent == null ? "%" :  idParent;
            LastNameChild = LastNameChild == null ? "%" : "%" + LastNameChild + "%";
            idchild = idchild == null ? "%" : idchild;
            WorkWithDB workWithDB = new WorkWithDB();
            FindedParents = workWithDB.getParents(LastName, idParent, LastNameChild, idchild);
            return View("ParentsConnections");
        }
        public ViewResult myAccount()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ChangeInfo(string LastName, string FirstName, string Patronymic, DateTime birthday, IFormFile upload)
        {
            thisAccount.lastName = LastName;
            thisAccount.name = FirstName;
            thisAccount.patronymic = Patronymic;

            if (upload != null)
            {
                string newName = $"avatar{id}";
                // путь к папке Files
                string path = "/avatars/" + newName + Path.GetExtension(upload.FileName);
                // сохраняем файл в папку Files в каталоге wwwroot
                using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
                {
                    await upload.CopyToAsync(fileStream);
                }
                thisAccount.avatar = path;
            }
           
            WorkWithDB workWithDB = new WorkWithDB();
            try
            {
                workWithDB.updateUser(thisAccount);
                if (!AccountController.current.email.Equals(""))
                {
                    string message = "<h2>Изменение персанальных данных прошло успешно!</h2>" +
                        $"<p> Фамилия: <b>{AccountController.current.lastName}</b> </p> " +
                        $"<p> Имя: <b>{AccountController.current.name}</b> </p>" +
                        $"<p> Отчество: <b>{AccountController.current.patronymic}</b> </p>" +
                        $"<p> Дата рождения: <b>{AccountController.current.birthday}</b> </p>" +
                        $"<h3>Если это были не вы срочно обратитесь к разработчику ответив на это письмо</h3>" +
                         $"<hr><p>Дата и время изменений: {DateTime.Now.ToString()}</p> " +
                         $"<p></p>";
                    mailbot.send(AccountController.current.email, "Изменение данных", message);
                }
            }
            catch(Exception ex)
            {
                ViewBag.message = ex.Message == null ? workWithDB.catchStatus : ex.Message;
            }
            return View("myAccount");
        }
        public ViewResult changePassword(string oldpassword, string password)
        {
            string message = "";
            if (AccountController.current.password.Equals(oldpassword))
            {
                try
                {
                    WorkWithDB workWithDB = new WorkWithDB();
                    workWithDB.UpdatePassword(AccountController.current.id, password);
                    ViewBag.message = "Пароль успешно изменен!";
                    AccountController.current.password = password;
                    message = "<h2>Был изменен пароль на вашем аккаунте</h2>" +
                        $"<p> Ваш новый пароль: <b>{password}</b> </p> " +
                        $"<h3>Если это были не вы срочно обратитесь к разработчику ответив на это письмо</h3>" +
                         $"<hr><p>Дата и время изменения пароля: {DateTime.Now.ToString()}</p> " +
                         $"<p></p>";

                }
                catch(Exception ex)
                {
                    ViewBag.message = ex.Message;
                }
                
            }
            else
            {
                message = "<h2>Была неудачная попытка изменения пароля в аккаунте</h2>" +
                       $"<p>Если это были не вы срочно обратитесь к разработчику ответив на это письмо</p>" +
                        $"<hr><p>Дата и время попытки изменения пароля: {DateTime.Now.ToString()}</p>";
                ViewBag.message = "Старый пароль введен не верно!";
            }
            if (!AccountController.current.email.Equals(""))
            {
                mailbot.send(AccountController.current.email, "Изменение пароля", message);
            }
            return View("myAccount");
        }
        public ViewResult changeLogIn(string email, string number, string SecretWord)
        {
            AccountController.current.email = email == null ? "" : email;
            AccountController.current.number = number;
            AccountController.current.secretWord = SecretWord;
            WorkWithDB work = new WorkWithDB();
            try
            {
                work.updateUser(AccountController.current);
                if (!AccountController.current.email.Equals(""))
                {
                    string message = "<h2>Изменение данных для восстановления пароля прошло успешно!</h2>" +
                        $"<p> E-mail: <b>{AccountController.current.email}</b> </p> " +
                        $"<p> Номер телефона: <b>{AccountController.current.number}</b> </p>" +
                        $"<p> Секретное слово: <b>{AccountController.current.secretWord}</b> </p>" +
                        $"<p> После прочтения данного сообщения пожалуйста удалите его. Тут содержиться очень важная информация</p>" +
                        $"<h3>Если это были не вы срочно обратитесь к разработчику ответив на это письмо</h3>" +
                         $"<hr><p>Дата и время изменений: {DateTime.Now.ToString()}</p> " +
                         $"<p></p>";
                    mailbot.send(AccountController.current.email, "Изменение данных", message);
                }
            }
            catch(Exception e)
            {
                ViewBag.message = e.Message;
            }
            return View("myAccount");
        }
        public ViewResult getFindedParent(string LastName, string FirstName, string Patronymic)
        {
            LastName = LastName == null ? "%" : "%" + LastName + "%";
            FirstName = FirstName == null ? "%" : "%" + FirstName + "%";
            Patronymic = Patronymic == null ? "%" : "%" + Patronymic + "%";
            WorkWithDB workWithDB = new WorkWithDB();
            FindedParents = workWithDB.getParents(LastName, FirstName, Patronymic);
            return View("Parents");
        }
        public IActionResult getStatements()
        {
            WorkWithDocs doc = new WorkWithDocs();
            return doc.CreateStatementsChange(thisAccount.lastName + thisAccount.id +"_"+ DateTime.Now.ToString("dd_mm_yyyy HH:mm"), thisAccount);
        }
        
    }
}

School/Views/Client/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using School.Controllers;
@using School.Data.Models;
@{
    ViewBag.Title = "Добро пожаловать!";
    Layout = "~/Views/_LayoutClient.cshtml";
    Person current = AccountController.current;
}

<p class="text-index-p">Добро пожаловать <b>@current.lastName @current.name @current.patronymic</b></p>
<p class="text-index-p">Вы @if (current.position.Equals("Сотрудник"))
{
    <b>@current.fullPosition</b>
}
else
{
       <b>@current.position</b>
}
    </p>
<p class="text-index-p">Ваш уровень доступа <b>@current.level из 7</b></p>
<p class="text-index-p">Выберайте пункты меню для работы с web-приложением</p>

School/Views/Client/Parents.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using School.Data.Models;
@using School.Controllers; 
@{
    ViewBag.Title = "Родители";
    Layout = "~/Views/_LayoutClient.cshtml";
    WorkWithDB workWithDB = new WorkWithDB();
    List<Person> Parents = ClientController.FindedParents;
}

<div class="parents-conroll to-animate">
    <div class="table-element">
        <table class="table-element-parents">
            <tr>
                <th>Фамилия</th>
                <th>Имя</th>
                <th>Отчество</th>
                <th>Пол</th>
                <th>День рождения</th>
                <th>Номер телефона</th>
                <th>E-mail</th>
                <th>ID ребенка</th>
                <th>ФИО ребенка</th>
                <th>Класс</th>
            </tr>
            @foreach (var p in Parents)
            {
            <tr>
            <td>@p.lastName</td>
            <td>@p.name</td>
            <td>@p.patronymic</td>
            <td>@p.sex</td>
            <td>@p.birthday</td>
           
                <td><a href="tel:@p.number">@p.number</a></td>
                <td><a href="mailto:@p.email">@p.email</a></td>

                <td>@p.child.id</td>
                <td>@p.child.lastName @p.child.name[0] @if (!p.child.patronymic.Equals(""))
                                                        {
                                                             @p.child.patronymic[0]
                                                         }</td>
                <td>@p.child.ScClass</td>
             
            
        </tr>
            }
        </table>
    </div>
    <div class="cotrollTable">
        <form action="getFindedParent">
            <input class="simpleText" name="LastName" type="text" placeholder="Фамилия">
            <input class="simpleText" name="FirstName" type="text" placeholder="Имя">
            <input class="simpleText" name="Patronymic" type="text" placeholder="Отчество">
            <div class="submit">
                <input type="submit" value="Поиск">
            </div>
        </form>
        
        </div>
    </div>

School/Views/Client/ParentsConnections.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using School.Data.Models;
@using School.Controllers;
@{
    ViewBag.Title = "Родители";
    Layout = "~/Views/_LayoutClient.cshtml";
    List<Person> Parents = ClientController.FindedParents;

}
<div class="parents-conroll to-animate">
    <div class="table-element">
        <table class="table-element-parents">
            <tr>
                <th>id Родителя</th>
                <th>ФИО Родителя</th>
                <th>ID ребенка</th>
                <th>ФИО ребенка</th>
                <th>Класс</th>
            </tr>
            @foreach (var p in Parents)
            {
                <tr>
                    <td>@p.id</td>
                    <td>
                        @p.lastName @p.name[0] @if (!p.patronymic.Equals(""))
                        {
                            @p.patronymic[0]
                        }
                    </td>
                    <td>@p.child.id</td>
                    <td>
                        @p.child.lastName @p.child.name[0] @if (!p.child.patronymic.Equals(""))
                        {
                            @p.child.patronymic[0]
                        }
                    </td>
                    <td>@p.child.ScClass</td>

                </tr>
            }
        </table>
    </div>
    <div class="cotrollTable">
        <div class="sub-head">
            <p><font color="maroon"><b>@ViewBag.ConnectionPC</b></font></p>

        </div>
        <form action="setConnection">
            <input class="simpleText" name="idParent" type="number" min="0" placeholder="id родителя" required>
            <input class="simpleText" name="idChild" type="number" min="0" placeholder="id ребенка" required>
            <div class="submit">
                <input type="submit" value="Связать">
            </div>
        </form>
        <form action="getExFindedParent">
            <input class="simpleText" name="LastName" type="text" placeholder="Фамилия родителя">
            <input class="simpleText" name="idParent" type="number" min="0" placeholder="id родителя">
            <input class="simpleText" name="LastNameChild" type="text" placeholder="Фамилия ребенка">
            <input class="simpleText" name="idchild" type="number" min="0" placeholder="id ребенка">

            <div class="submit">
                <input type="submit" value="Поиск">
            </div>
        </form>

    </div>
</div>

School/Views/Client/myAccount.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using School.Controllers;
@using School.Data.Models;
@{
    ViewBag.Title = "Мой аккаунт";
    Layout = "~/Views/_LayoutClient.cshtml";
    Person thisPerson = AccountController.current;
    DateTime date = Convert.ToDateTime(AccountController.current.birthday);
    string avaPath = "/images/avatar.png";
    if (!AccountController.current.avatar.Equals(""))
    {
        avaPath = AccountController.current.avatar;
    }
}
<div class="maElements">
    <div class="notEditedInfo maBorder">
        <h3 class="mah3" style="text-align: center; ">Общая информация</h3>
        <p>Ваш ID: <b>@thisPerson.id</b></p>
        <p>Логин: <b>@thisPerson.username</b></p>
        <p>Уровень доступа: <b>@thisPerson.level</b></p>
        <p>Пол: <b>@thisPerson.sex</b></p>
        @if (thisPerson.level > 2)
        {
            <p>Должность: <b>@thisPerson.fullPosition</b></p>
        }
        else
        {
            <p>Статус: <b>@thisPerson.position</b></p>
        }
    <a class="a-to-button to-animate" href="/Client/getStatements">Запрос на изменение</a>
    </div>
    <div class="maFIO maBorder">
        <h3 class="mah3" style="text-align: center; ">Персональная информация</h3>
        <form action="ChangeInfo" asp-action="ChangeInfo" asp-controller="Client" method="post" enctype="multipart/form-data">
            <div class="default-info">
                <div class="subdiv">
                    <input class="simpleText" name="LastName" type="text" placeholder="Фамилия" title="Фамилия должна начинаться с большой русской буквы" pattern="[А-Я]{1}[а-я]{1,}" value="@AccountController.current.lastName" required>
                    <input class="simpleText" name="FirstName" type="text" placeholder="Имя" title="Имя должно начинаться с большой русской буквы" pattern="[А-Я]{1}[а-я]{1,}" value="@AccountController.current.name" required>
                    <input class="simpleText" name="Patronymic" type="text" placeholder="Отчество" title="Отчество должна начинаться с большой русской буквы" pattern="[А-Я]{1}[а-я]{3,}" value="@AccountController.current.patronymic">
                </div>
                <div class="subdiv">
                    <input class="simpleText" name="birthday" type="date" title="Дата рождения" value="@date.ToString("yyyy-MM-dd")"
                           required>
                    <!--
                    <input class="simpleText" name="email" type="email" placeholder="E-mail" value="@AccountController.current.email">
                    <input class="simpleText" name="number" type="tel" pattern="\+375\([0-9]{2}\)[0-9]{3}-[0-9]{2}-[0-9]{2}"
                           placeholder="Номер телефона" title="+375(XX)XXX-XX-XX" value="@AccountController.current.number" required>-->
                    <img class="ava" src="@avaPath" height="125" width="125" />
                    <input type="file" name="upload" accept="image/*"/>
                         
                </div>
            </div>
            
            <div class="submit">
                <input class="to-animate" type="submit" value="Сохранить">
            </div>
        </form>
    </div>
    <div class="ChangePassword maBorder">
        <h3 class="mah3" style="text-align: center; ">Смена пароля</h3>
        <form action="changePassword" method="post" name="form1">

            <input class="password" name="oldpassword" type="password" placeholder="Старый пароль" required>
            <input class="password" name="password" type="password" placeholder="Новый пароль" autocomplete="new-password" pattern="[0-9a-zA-Z]{8,16}" title="Пароль должен состоять из английских букв и цифр. От 8 до 16 символов" required>
            <input class="password" name="conirmPassword" type="password" placeholder="Подтвердите пароль" autocomplete="new-password" onchange="checkin(form1)" required>
            <script>
                function checkin(obj) {
                    var a = obj.password.value;
                    var b = obj.conirmPassword.value;
                    if (a != b) {
                        alert("Пароли не совпадают!");
                        obj.conirmPassword.value = "";
                    }
                }</script>
            <p class="small-p"><b>@ViewBag.message</b></p>
            <div class="submit">
                <input class="to-animate" type="submit" value="Сохранить">
            </div>
        </form>
    </div>
    <div class="ChangeLogIn maBorder">
        <h3 class="mah3" style="text-align: center; ">Данные для восстановления пароля</h3>
        <form action="changeLogIn" method="post" name="form1">
            <input class="simpleText" name="email" type="email" placeholder="E-mail" value="@thisPerson.email">
            <input class="simpleText" name="number" type="tel" pattern="\+375\([0-9]{2}\)[0-9]{3}-[0-9]{2}-[0-9]{2}" placeholder="Номер телефона" title="+375(XX)XXX-XX-XX" value="@thisPerson.number" required>
            <input class="simpleText" name="SecretWord" type="text" placeholder="Кодовое слово" title="Кодовое слово может состоять из любых символов" value="@thisPerson.secretWord" required>
            
            <div class="submit">
                <input class="to-animate" type="submit" value="Сохранить">
            </div>
        </form>
    </div>
</div>